[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.zksync]
compile = true
mode = "3"  # zkSync optimization mode

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
